### ISSUE TITLE
optInParams() argument type problems

### ISSUE THREAD

**Issue by alectogeek** [tenjin/flutter-sdk#1]
I receive the following exception:

```
E/MethodChannel#tenjin_sdk(32629): Failed to handle method call
E/MethodChannel#tenjin_sdk(32629): java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String[]
E/MethodChannel#tenjin_sdk(32629): 	at com.tenjin_sdk.TenjinSdkPlugin.optInParams(TenjinSdkPlugin.kt:105)
E/MethodChannel#tenjin_sdk(32629): 	at com.tenjin_sdk.TenjinSdkPlugin.onMethodCall(TenjinSdkPlugin.kt:40)
E/MethodChannel#tenjin_sdk(32629): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#tenjin_sdk(32629): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#tenjin_sdk(32629): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#tenjin_sdk(32629): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#tenjin_sdk(32629): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#tenjin_sdk(32629): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#tenjin_sdk(32629): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#tenjin_sdk(32629): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#tenjin_sdk(32629): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#tenjin_sdk(32629): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/TenjinInstallReferrer(32629): Install Referrer - FEATURE_NOT_SUPPORTED: 2

E/flutter (32629): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, java.util.ArrayList cannot be cast to java.lang.String[], null, java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String[]
E/flutter (32629): 	at com.tenjin_sdk.TenjinSdkPlugin.optInParams(TenjinSdkPlugin.kt:105)
E/flutter (32629): 	at com.tenjin_sdk.TenjinSdkPlugin.onMethodCall(TenjinSdkPlugin.kt:40)
E/flutter (32629): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (32629): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (32629): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (32629): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (32629): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (32629): 	at android.os.Looper.loop(Looper.java:160)
E/flutter (32629): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter (32629): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32629): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (32629): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (32629): )
E/flutter (32629): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (32629): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (32629): <asynchronous suspension>
E/flutter (32629): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (32629): #3      TenjinSDK.optInParams (package:tenjin_sdk/tenjin_sdk.dart:40:16)
E/flutter (32629): #4      main (package:myApp/main.dart:74:22)
E/flutter (32629): <asynchronous suspension>
E/flutter (32629): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (32629): #6      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (32629): #7      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (32629): #8      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (32629): #9      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (32629): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (32629): #11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (32629): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (32629):

```

**Comment by thize** [comment]
Thanks!, solved
